dist: trusty
sudo: required
language: java
env:
  global:
  - LANG: hin
  - LANGTWO: bih
  - GITHUB_REPO: Shreeshrii/tess4eval
git:
  depth: 3
cache:
  directories:
  - imagesbih-save
  - imageshin-save
  - jar
  - tess4-save
  - tess4data-save
before_script:
- echo "before script, bash ./0createcache.sh"
script:
- bash ./1createcache.sh
- bash ./2installesseract.sh
- bash ./3get-gh-pages.sh
- bash ./4runtesseract.sh
- java -cp ./jar/ocrevaluation.jar  eu.digitisation.Main  -gt ./gt -ocr ./$LANG  utf8   -d   ./out
- mv ./out/gt_out.html ./out/gt_$LANG.html
- java -cp ./jar/ocrevaluation.jar  eu.digitisation.Main  -gt ./gt -ocr ./$LANGTWO  utf8   -d   ./out
- mv ./out/gt_out.html ./out/gt_$LANGTWO.html
- bash ./6deploy.sh
- bash ./7update-gh-pages.sh
