dist: trusty
sudo: required
language: java
git:
  depth: 3
cache:
  directories:
  - imagesbih-save
  - imageshin-save
  - jar
  - tess4-save
  - tess4data-save
before_script:
- ls jar
- ls tess4-save
- ls tess4data-save
- ls imageshin-save/imageshin
- ls imagesbih-save/imagesbih
script:
- bash ./installtesseract.sh
- bash ./runtesseract.sh
- java -cp ./jar/ocrevaluation.jar  eu.digitisation.Main -gt ./gt -ocr ./ocr utf8 -d ./out
- bash ./deploy.sh
env:
  global:
  - GITHUB_REPO: Shreeshrii/tess4eval
  - secure: ctS1ZjBVdA/rGlajuvGvydYN3Fq59VXCB8R7fw1w1GPOHUYo1NfcX+PAOIk3gh9UysrZoInv7tqCXolferCOgCSaJmQV6FWJzyQBpZbTAN0kzUEE5l2QHEzqDS278F5Q/oByOMGSQ9o5M0Q9mxsFCLeebAis85svzXv60hitn53XJGxuWMriPMv7Sjxq23Iiqb4GV5CmS1zJISx3ZG1zaEqLeORSvtTVtAY39lSW5iFamdvi4jEyaas14tvY8s5eUq6Na+/VIeA6NL26Rocpbd9+0zclAeEhFB0RvG3uBIFXCJwIdT5gH4+9GrJHU+kCPHgCzLcuq2WvnO75CHRp2sUuhMwiWvnjfCF47C31aaYJpXzt/AbPyNescmf52DjNWzs+QR/RRECGjEMp4JEgZkZtm3e6Kzg5ix/BGEJ96iY7Qru/vNsvvspp9W39xe389ECknTRqPrpuVNDn0Kq/cNOwjkKKTyakdXzt8vdRJRe/wZK6oDNc8680DimN9K3LgVPsl4lXdtGLXhKbgOOjiehhi4Pf7zX9pVprhFCTqQKflM4nHoa7XbU80RJbBJCgLxULxq0sWN15ObjLTuQ9UeBwTufJd6GlaGH5JoHZt0STSUwZaHu1f7bGJ3Y9eml8cFShejlQy4BHxzSPGanadx/IYUCHTBHqN8cLmnUc6Ls=
