dist: trusty
sudo: required
language: java
env:
  global:
  - LANG: hin
  - LANGTWO: bihtune
  - GITHUB_REPO: Shreeshrii/tess4eval
git:
  depth: 3
cache:
  directories:
  - imagesbih-save
  - imageshin-save
  - imagessan-save
  - imagesdeva-save
  - jar
  - tess4-save
  - tess4data-save
  - tess4dev-save

before_install:
#- bash ./0createcache.sh
- bash ./1createcache.sh

install:
- bash ./2installtesseract.sh

before_script:
- bash ./3get-gh-pages.sh
#- bash ./4runtesseract.sh # hindi and bihari images
- bash ./5runtesseract.sh # sanskrit images

script:
- java -cp ./jar/ocrevaluation.jar  eu.digitisation.Main  -gt $TRAVIS_BUILD_DIR/gt -ocr $TRAVIS_BUILD_DIR/$LANG     utf8 -d $TRAVIS_BUILD_DIR/out
- mv $TRAVIS_BUILD_DIR/out/gt_out.html $TRAVIS_BUILD_DIR/out/gt_$LANG.html
- java -cp ./jar/ocrevaluation.jar  eu.digitisation.Main  -gt $TRAVIS_BUILD_DIR/gt -ocr $TRAVIS_BUILD_DIR/$LANGTWO  utf8 -d $TRAVIS_BUILD_DIR/out
- mv $TRAVIS_BUILD_DIR/out/gt_out.html $TRAVIS_BUILD_DIR/out/gt_$LANGTWO.html

after_script:
- bash ./6deploy.sh
- bash ./7update-gh-pages.sh
