dist: trusty
sudo: required
language: java
git:
  depth: 3
cache:
  directories:
  - imagesbih-save
  - imageshin-save
  - jar
  - tess4-save
  - tess4data-save
before_script:
- ls jar
- ls tess4-save
- ls tess4data-save
- ls imageshin-save/imageshin
- ls imagesbih-save/imagesbih
script:
- bash ./installtesseract.sh
- bash ./runtesseract.sh
- java -cp ./jar/ocrevaluation.jar  eu.digitisation.Main -gt ./gt -ocr ./ocr utf8
  -d ./out
- bash ./deploy.sh
env:
  global:
  - GITHUB_REPO: Shreeshrii/tess4eval
  - secure: omxXBV1C86IxhH9G6EIjAZYXJw+MFvKXAGErDZo8uFwVfpJOn/nm457/2aLh5+tOjQPiI/RhXh8KFvcVa8JJIG8+bpQgv6soJbYtNL8lRHc1YXC+r6SkkBpGYOgAicCayYB1JyVuOSzIZ1GB03a9Lo2lJqio33Lbv8Hqo4KwaZGB2wdwdWzESYoCaqcfegcVmU3uR4+pnYtmOIpkNha99vppOJNocWSA93F9QCGNGQtdiRyRkM/h1jtq1xJ3fUnV0b1vK6PP1SMGJvU0nKvf4ewGGHsMurSBQATbyk75JHzKz5KdtZ10OBU0thCUPKF2xfNijfLCW5OlZZOgtuB6vPDkd4m5hTgvNLT3408xGB2esrN7t6ApPrpAFVTcdR7327DWZZVBWPl/C/KliGQOkd2zFBEQfDiNZdSylwDQNpCpu3+G2vKE4FNm9QGfijjJgIsG4A+8L2wyPnnYOOcw2R/X4ruAIUnzH+LDEOm3waT/S5BxK0yAqjbSX8tQi3FY9j3d+HyHlEgLr7pEEIIVX37ACxhnFtI1TxUiajDyKjIliLSeOlmibn120gDLcnc7WaZWwxym1LttaWierUAScLOj0BrNBoxebTMv8OC2q4LdO6Ty7MF4XyWiwBYw/ZlJMDZ8nA6mCQru5ZUtyzKwpx7Ir6N9tL8pllwxIYQtM6M=
  - secure: W92GwTDVHNYzolbTapGuk0L1VCvHK9LWtVgDOkYZmK0Qip3os8QL6XT5AEu9qWiUBO0q0o3O5RDiwgf3/K+no4D65B5byrwvqjTD0JpjKnXhuR36F+nX4to6YfIy5yS8LtH/xH/v+BWbDAAYhCcREJ55aPwV2OAtJ5tPKWRQAGQt3o3bveEcjiUcJb1mpz6poODBdZbPgNcu93xK7x4Wn+g2yTUGvCzYWri7VfB7bacNiO6V4UfkTn9oCvJTm2JGO0xTfABvnLbZWBPJFIRH3MadutqXTy9m5xmaHIvZNHLZFgSsSJDVhI4usSA6hFyyyK8p30ackEJ2Wbo1S7MDp01lkkGLoaIPY3CoQT3UsE+tHgw8TSI0W3y2jy+D2KQOLMMnPUXDOWDBjrF+AO7II7GrBAuFoGj4kDZYtCVGQU9DlLFjPr02pReK9QX37h2q4VjvIhp9hlvymuX9NbC1xUO8RgMtoKRpweK/7B49XS6keGidL5/lkC5wYt3X6FJNDBFGSdHMgAoaARzGyOHycDovS5knKH31gi0cB+Mz7EnreyzSWApWvJObXqjON+FHD+2mAuKmNp5egbSHKDcHFeYvXm8i6QgDypAgJUIrtpfnPPSGHNsIkunNP3CfxBQixZlWZtpJBRgQztQPK+e3qr09xO7HM+CL2WZopfgOoIk=
  - secure: db9Q5frPbujs7mrrT67DU/qUKhWxA4P1lehJgW19i6hweD+a7Gv6qOLDnY796CI6OM6ExHdv5pkcScPEbgbDTR0HJ9x4l6uTS6xmrb90A+HXuGlEz/Gl8AcxrRSyI/0ByfTQVs4wK5qsMFV+vHcYY0keydLwSNbPLbkjgldWPutRVh7JqS6h93dydyXiyYgdGi3zv/f+M83xGn2am3zRi6ycj1ejBV+ZIh5QYae7ZZn5URJhC0a0oxWik/87s/OJNNj9IyLXVHLfrroV+Pd3/J+3P7L6xd8J6D8fvhWmCojB1MKdaMVdjeQVljPGRX47lt5DChu6oMzrVnz7YRRtteqcSfwtv7mnjfTHra5Cy+DhtaqJE3q18XCihF9nnb07itntgthymilrfn8CRFoaK0HTM2TQ/eFaWpMhlglwmUJNjszHGneEsvMIv5FOIBn6GnXwhr6QsWzlH5rYEk2xBILr/s/ylJExqK/oz1+UEJYVUoxdQFBM/nQxasD80igG/QGtkBL//nbrRWhze0T+jT/z9joWOiGTsaWnsSinbwP5Oa21+2Cq8sTtyIa5+sHeleYCj0GxKR115xTQE4bFg6QvlwwRGd6OhwPrfmyXAhFXH6E+rRcuXaOwuah1AB4v3CbhzSIRtX8P/s6PDKbuMk6AklkVbP7Do+82OTOL5cI=
