dist: trusty
sudo: required
language: java
env:
  global:
  - GITHUB_REPO: Shreeshrii/tess4eval
git:
  depth: 3
cache:
  directories:
  - imagesbih-save
  - imageshin-save
  - jar
  - tess4-save
  - tess4data-save
before_script:
- echo "before script, add create cache here, when needed"
script:
- bash ./installtesseract.sh
- bash ./runtesseract.sh
- java -cp ./jar/ocrevaluation.jar  eu.digitisation.Main -gt ./gt -ocr ./ocr utf8
  -d ./out
- bash ./deploy.sh
